name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/coleam00/bolt.new-any-llm.git

      - name: Fetch and Merge Updates
        run: |
          git fetch upstream
          git checkout main
          # Reset commit.json to match upstream
          git reset -- app/commit.json
          git checkout upstream/main -- app/commit.json
          # Add and commit the changes to commit.json
          git add app/commit.json
          git commit -m "Update commit.json from upstream"
          # Now merge the rest
          git merge --allow-unrelated-histories -X theirs upstream/main
          git push origin main

  deploy:
    needs: sync
    environment: prod
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@v1.5.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: bolt
          directory: build/client
          secrets: |
            OPENAI_API_KEY
            ANTHROPIC_API_KEY
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
