name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/coleam00/bolt.new-any-llm.git

      - name: Fetch and Merge Updates
        run: |
          git fetch upstream
          git checkout main
          # Always accept upstream changes for commit.json
          git checkout upstream/main app/commit.json
          # Allow merging unrelated histories and force theirs strategy
          git merge --allow-unrelated-histories -X theirs upstream/main
          git push origin main