name: Sync Fork

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Fork
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Add Upstream Remote
        run: git remote add upstream https://github.com/coleam00/bolt.new-any-llm.git

      - name: Fetch and Merge Updates
        run: |
          git fetch upstream
          git checkout main
          # Reset commit.json to match upstream
          git reset -- app/commit.json
          git checkout upstream/main -- app/commit.json
          # Add and commit the changes to commit.json
          git add app/commit.json
          git commit -m "Update commit.json from upstream"
          # Now merge the rest
          git merge --allow-unrelated-histories -X theirs upstream/main
          git push origin main
